# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

use_frameworks!

target 'BaseballGame' do
    pod 'UCZProgressView'
    pod 'hpple'
    pod 'MGSwipeTableCell'
    pod 'ZFDragableModalTransition'
    pod 'DownloadButton'
end

target 'BaseballGameTests' do

end

target 'BaseballGameUITests' do

end

