# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'BaseballGame' do
    pod 'UCZProgressView'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
end

target 'BaseballGameTests' do

end

target 'BaseballGameUITests' do

end

